sudo: required
services:
  - docker

before_install:
  - docker build -t markjpk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markjpk/react-test npm run test

after_success:
  - docker build -t markjpk/multi-client ./client
  - docker build -t markjpk/multi-nginx ./nginx
  - docker build -t markjpk/multi-server ./server
  - docker build -t markjpk/multi-worker ./worker