sudo: required
services:
  - docker

before_install:
  - docker build -t markjpk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markjpk/react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "Multi-docker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-142272235652"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"